export const selectors = {
    course:'#lms-course',
    slide : '.lms-slide',
    audioPlayerControl: '#lms-slide-control-player',
    audioGridBlock: '.lms-grid-block[data-audio-src]',
    courseControlsAudio: '.lms-slide-control-audio',
    preloader: '#lms-course-loader',
    courseControls: '.lms-course-controls',
    slideNavigation: '.lms-slide-control-navigation',
    sectionNavigation: '.lms-section-control-navigation',
    courseControlsFullscreen: '.lms-slide-fullscreen',
    fullscreenOptions : '.lms-slide-control-fullscreen-option',
    gridBlock :'.lms-grid-block',
    progressBar: '.lms-course-progress',
    quizHint : '.lms-quiz__hint',
    quizFormOptions : '.lms-quiz-form-options',
    quizFormTextField : '.lms-quiz-form-text_field',
    quizFormTextArea : '.lms-quiz-form-text_area',
    quizCheckPuzzle : '.lms-check-puzzle',
    quizCheckDnD : '.lms-check-dnd',
    quizForm : '.quiz-form',
    puzzleGrid : '.lms-puzzles-grid',
    puzzleGridItem : '.lms-puzzles-grid__item',
    dndQuiz : '.lms-dnd-quiz',
};